import "file:///home/reagan/github/music-dog/src/events/ready.ts#0";
import "file:///home/reagan/github/music-dog/src/events/guildCreate.ts#0";
import "file:///home/reagan/github/music-dog/src/events/mod.ts#0";
import "file:///home/reagan/github/music-dog/src/events/messageCreate.ts#0";
import "file:///home/reagan/github/music-dog/src/events/interactionCreate.ts#0";
import "file:///home/reagan/github/music-dog/src/commands/play.ts#1";
import "file:///home/reagan/github/music-dog/src/commands/mod.ts#1";
import "file:///home/reagan/github/music-dog/src/handlers/mod.ts#2";
import "file:///home/reagan/github/music-dog/src/handlers/youtube.ts#2";